### ISSUE TITLE
Add script and data information to ReadMe

### ISSUE THREAD

**Issue by PietrH** [AgentschapPlantentuinMeise/MIDSCalculator#4]
Lynn should better document what she is doing in the Repo, this is also good practice.

## Todo:

- [ ] What do these scripts all do?
- [ ] What are the datasets used for
- [ ] Where are the datasets from?
